### ISSUE TITLE
Working abnormally. Nothing appears after clicking "Start"

### ISSUE THREAD

**Issue by lcy92** [zzpong/Interactive-ASM-Cheats-Updater#14]
Hi 
Thanks for your tool. 

I encounter the issue with the v1.1.1f release that it didn't work after I clicked "Start" button. Nothing was generated.
![image](https://github.com/user-attachments/assets/aaa026aa-ee99-47a2-baf5-401ca76d418f)

By checking the log file under "log" folder, there are error messages :

[2024-07-12 22:59:16,377] ERROR: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "utilities\interface.py", line 1348, in generate
  File "utilities\code_structer.py", line 110, in __init__
  File "utilities\code_structer.py", line 449, in generate_code_struct
  File "utilities\code_structer.py", line 523, in analyse_single_code
ValueError: too many values to unpack (expected 2)

Please suggest. Thanks.

**Comment by zzpong** [comment]
Can you upload those main file and cheat codes here?

**Comment by lcy92** [comment]
Here they are


[2E3EAEB4B6834BEF.txt](https://github.com/user-attachments/files/16195953/2E3EAEB4B6834BEF.txt)
[main_files.7z.001.txt](https://github.com/user-attachments/files/16196094/main_files.7z.001.txt)
[main_files.7z.002.txt](https://github.com/user-attachments/files/16196105/main_files.7z.002.txt)
[main_files.7z.003.txt](https://github.com/user-attachments/files/16196110/main_files.7z.003.txt)

**Comment by zzpong** [comment]
Thanks! Woking on it.

**Comment by zzpong** [comment]
Thank you for your feedback. The bug has been fixed. Please download the attachment below and cover the original execute file.
[main_en.zip](https://github.com/user-attachments/files/16196392/main_en.zip)

**Comment by lcy92** [comment]
Thank you for fixing it with amazing speed!
