### ISSUE TITLE
V1.0.2 Unhandled exception Error

### ISSUE THREAD

**Issue by Warborn123** [zzpong/Interactive-ASM-Cheats-Updater#7]
Hi, V1.0.2 gives me this error message every time I try to run it:

Failed to execute script '_main_' due to unhandled exception:
‘Nonelype' object has no attribute ‘write’

Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "utilities\interface.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "utilities\game_package.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "utilities\NszDecompressor.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nsz\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nsz\Fs\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nsz\Fs\Nsp.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nsz\nut\Keys.py", line 174, in <module>
  File "nsz\nut\Print.py", line 28, in error
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by zzpong** [comment]
Your key version doesn't match the nsz version. Please use the key.txt file in the same release package.

**Comment by Warborn123** [comment]
> Your key version doesn't match the nsz version. Please use the key.txt file in the same release package.

This is before I load any nsz/nsp package. This error message show up when I double click the .exe file. The key file in the yuzu folder is OS17.0.0. Also, V1.0.1 doesn't give me this error.

**Comment by zzpong** [comment]
Yep, the same problem. Please use the key.txt file in the same release package.

**Comment by Warborn123** [comment]
> Yep, the same problem. Please use the key.txt file in the same release package.

Alright, I see. Thank you. I just realised that the version you released on github is fine, but the version on gbatemp.net doesn't have the key.txt file in it.
